/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface ReusableAvatar {
    'articles': number;
    'avatarUrl': string;
    'friends': number;
    'groups': number;
  }
}

declare global {


  interface HTMLReusableAvatarElement extends Components.ReusableAvatar, HTMLStencilElement {}
  var HTMLReusableAvatarElement: {
    prototype: HTMLReusableAvatarElement;
    new (): HTMLReusableAvatarElement;
  };
  interface HTMLElementTagNameMap {
    'reusable-avatar': HTMLReusableAvatarElement;
  }
}

declare namespace LocalJSX {
  interface ReusableAvatar {
    'articles'?: number;
    'avatarUrl'?: string;
    'friends'?: number;
    'groups'?: number;
  }

  interface IntrinsicElements {
    'reusable-avatar': ReusableAvatar;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'reusable-avatar': LocalJSX.ReusableAvatar & JSXBase.HTMLAttributes<HTMLReusableAvatarElement>;
    }
  }
}


